
# ç«™ç‚¹é…ç½®
baseURL = "https://algo-cpp.rogery.dev"
languageCode = "zh"
title = "Roger Young"
theme = "hugo-pure"

# å¯ä»¥åˆ é™¤ç”¨ä¸åˆ°çš„é…ç½®ï¼Œä¸å»ºè®®ç§»åŠ¨é¡ºåº

# åº•éƒ¨ç‰ˆæƒä¿¡æ¯ï¼Œæ”¯æŒ md
Copyright = "Â© 2023 [Roger Young](https://rogery.dev)"

# Git Info
[build]
enableGitInfo = true


[markup.tableOfContents]
# <ol> ç›®å½•
ordered = true
[markup.highlight]
# ä¸å†…ç½® chroma çš„ css
noClasses = true
# å…³é—­ chroma é«˜äº®
codeFences = false
[markup.goldmark.render]
# å…è®¸ md æ’å…¥ html æ ‡ç­¾
unsafe = true
[markup.goldmark.extensions]
# é­”æ”¹çš„ hugo, è§ https://github.com/rogeryoungh/hugo-patch
LaTeX = true


# æ ‡é¢˜æ 
[params.header]
avatar = "https://rogery.dev/img/logo.png"
name = "rogeryoungh"
link = "https://rogery.dev/"


[[params.menu]]
name = "Home"
url = "/"

[[params.menu]]
name = "List"
url = "/post/base/"

[[params.menu]]
name = "Post"
url = "/post"

[[params.menu]]
name = "ğŸ¤© GitHub"
url = "https://github.com/rogeryoungh/algorithm-cpp"


# KaTeX å…¬å¼æ¸²æŸ“
[params.katex]
enable = true


# Prism ä»£ç é«˜äº®
[params.prism]
enable = true


# ç›®å½•
[params.toc]
enable = true


[outputs]
home = ["HTML", "RSS", "JSON"]
